steps:
  - id: upload-file
    uses: google-github-actions/upload-cloud-storage@main
    with:
      path: /home/manesachin0683
      destination: bgs://sachintest121

  # Example of using the output
  - id: uploaded-files
    uses: foo/bar@master
    env:
      file: ${{steps.upload-file.outputs.uploaded}}
